### ISSUE TITLE
jsonpath-rw dependency conflicts with hass dependencies

### ISSUE THREAD

**Issue by jjlawren** [home-assistant-ecosystem/home-assistant-cli#322]
I'm not positive this is related to the version of Home Assistant, but I've found the `jsonpath-rw` dependency pulled in by CLI causes runtime conflicts with the HA `rest` component which depends on `jsonpath`: https://github.com/home-assistant/home-assistant/issues/32284.

**Comment by jjlawren** [comment]
This appears to remain a valid issue.

**Comment by fabaff** [comment]
Yes, it's a valid issue. Was also, present for the Fedora package (but more that there `jsonpath-rw` 
 was not up-to-date and released over 5 years ago for the last time).

Home Assistant is strictly pinning the release of the dependency. For `hass-cli` I soften them to allow the installation in the same `venv`. The pinning causes issues if a dependency is also pinning the requirements. This leads to a race condition during the initialization process.

I will look into it.

**Comment by onkelbeh** [comment]
Is something going on here?
Sometimes I run into conflicts between jsonpath and jsonpath-rw
HA's Androidtv component has issues if jsonpath-rw is installed.
