### ISSUE TITLE
Please update Homebrew hass-cli from '0.9.0' to '0.9.1'

### ISSUE THREAD

**Issue by haakonstorm** [home-assistant-ecosystem/home-assistant-cli#339]
```
 λ brew info homeassistant-cli
homeassistant-cli: stable 0.9.0 (bottled), HEAD
```

**Comment by osks** [comment]
Yes, please! Issue #331 makes 0.9.0 unusable.

**Comment by fabaff** [comment]
Sorry, I can't help with this. I only maintain packages for Fedora 31/32 and EPEL8 (Centos & RHEL).

I can only suggest that you try it in the Homebrew repo: https://formulae.brew.sh/formula/homeassistant-cli#default

**Comment by haakonstorm** [comment]
Perhaps we need some @maxandersen magic to get `brew/hass-cli` up to 0.9.1 ?

**Comment by shaver** [comment]
It looks like @zachauten was the last to touch that formula--maybe they can help?

**Comment by shaver** [comment]
I submitted a PR at https://github.com/Homebrew/homebrew-core/pull/54704 that works for me, but it's my first homebrew submission so ymmv.

**Comment by shaver** [comment]
PR was pushed, so 0.9.1 is live. Recommend closing this!

**Comment by zachauten** [comment]
Thanks for that PR @shaver! Also if the maintainers of this project are interested, they can use this github action to keep homebrew up to date automatically https://github.com/mislav/bump-homebrew-formula-action.
