### ISSUE TITLE
Migrate to jsonpath-ng

### ISSUE THREAD

**Issue by fabaff** [home-assistant-ecosystem/home-assistant-cli#340]
`jsonpath-rw` is unmaintained for quite some time and the last release was made over 5 years ago. [`jsonpath-ng`](https://pypi.org/project/jsonpath-ng/) is the successor that is actively developed 

Should fix #322

**Comment by onkelbeh** [comment]
Is something going on here?
Sometimes I run into conflicts between jsonpath and jsonpath-rw
HA's Androidtv component has issues if jsonpath-rw is installed.
