### ISSUE TITLE
info command uses deprecated discovery_info API endpoint

### ISSUE THREAD

**Issue by mvdwetering** [home-assistant-ecosystem/home-assistant-cli#378]
When running the `hass-cli info` command it fails with the error `error: HTTPError: 404 Client Error: Not Found for url: http://192.168.178.123:8123/api/discovery_info`

The `discovery_info` endpoint has been deprecated (see https://www.home-assistant.io/blog/2021/10/06/release-202110/#breaking-changes Discvery API section) and removed in 2022.2.

**Comment by fharper** [comment]
Thanks for sharing, I was wondering why it wasn't working!

**Comment by ScottG489** [comment]
I did a little digging and here's some info on what should be use as an alternative (from Paulus himself):

https://community.home-assistant.io/t/2021-10-0-z-wave-s2-support-tuya-secure-esphome-and-400-new-icons/344457/59

**Comment by fabaff** [comment]
`discovery_info` basically gathered the details which are used to announce the presence of a Home Assistant instance in the local network (mDNS).

Looks like that `hass-cli info` command could be removed now.

**Comment by varenc** [comment]
note that `hass-cli info` is still listed in this project's README as [the very first command to try](https://github.com/home-assistant-ecosystem/home-assistant-cli?tab=readme-ov-file#usage). I thought something was broken for awhile until I realized that every other command worked fine.
