### ISSUE TITLE
0.9.5~0.9.6 missing from PyPI

### ISSUE THREAD

**Issue by Maxr1998** [home-assistant-ecosystem/home-assistant-cli#393]
It appears that the last version published on PyPI is still 0.9.4. I'd appreciate if the latest version could be pushed so that I can update the AUR package. Thanks!

**Comment by chenrui333** [comment]
Bump this!

**Comment by maxandersen** [comment]
@fabaff any reason we stopped publishing these? I think I can still publish to pypi but before I do (as I hit this issue myself now :) I wanted to check if some reason updates don't get published anymore?

**Comment by fabaff** [comment]
No reason. Looks like that I simple forgot to do it after I tested the NixOS packages.

**Comment by fabaff** [comment]
https://pypi.org/project/homeassistant-cli/0.9.6/

**Comment by fabaff** [comment]
Sorry for the delay.
